yelp_clone/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

  root to: "restaurants#index"

end

yelp_clone/app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

yelp_clone/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include WithUserAssociationExtension

  has_many :reviews, dependent: :destroy
  belongs_to :user

  validates :name, length: {minimum: 3}, uniqueness: true



  def build_review(attributes = {}, user)
    attributes[:user] ||= user
    reviews.build(attributes)
  end

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end
end

yelp_clone/app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant
  has_many :endorsements

  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

yelp_clone/app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  has_many :restaurants
  has_many :reviews


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name
      # user.image = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end
end

yelp_clone/app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    redirect_to restaurants_path
  end
  
end

yelp_clone/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include WithUserAssociationExtension
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

  # def updated
  #   @restaurant = Restuarant.find(params[:id])
  #   @restaurant.update(restaurant_params)
  #   redirect_to '/restaurants'
  # end

  def destroy
   @restaurant = Restaurant.find(params[:id])
   if @restaurant.user_id == current_user.id
     @restaurant.destroy
     flash[:notice] = 'Restaurant deleted successfully'
   else
     flash[:notice] = 'This is not your restaurant to delete'
   end
   redirect_to '/restaurants'
  end

end

yelp_clone/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include WithUserAssociationExtension
  before_action :authenticate_user!, :except => [:index, :show]


  def new

    if current_user.has_reviewed? @restaurant
      flash[:notice] = 'You have already reviewed this restaurant'
    end

    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review(review_params, current_user)


    
    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        # Note: if you have correctly disabled the review button where appropriate,
        # this should never happen...
        # redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
        flash[:notice] = 'You have already reviewed this restaurant'
        redirect_to '/'
      else
        # Why would we render new again?  What else could cause an error?
        render :new
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.user_id == current_user.id
      @review.destroy
      flash[:notice] = 'The review has been deleted'
    else
      flash[:notice] = 'The review can only be deleted by its creator'
    end
    redirect_to '/restaurants'
  end


  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

yelp_clone/app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

yelp_clone/app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

yelp_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>

<%= notice %>
<%= yield %>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Facebook Sign in", user_omniauth_authorize_path(:facebook) %>
<% end %>

</body>
</html>

yelp_clone/app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
    <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
    <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    <h3>Average rating: <%= restaurant.average_rating.to_f %></h3>
    <h3>Stars: <%= star_rating(restaurant.average_rating) %>
    <h3>Reviews for <%= restaurant.name %></h3>

    <% if restaurant.reviews.any? %>
      <ul>
        <% restaurant.reviews.each do |review| %>
          <li>
            <%= review.thoughts %>, <strong><%= review.rating %></strong>/5
            <p><%= pluralize review.endorsements.count, 'endorsement' %></p>
            <%= link_to "Endorse Review", review_endorsements_path(review), method: :post %>
            <%= link_to "Delete review", review_path(review), method: :delete %>
          </li>
        <% end %>
      </ul>
<% else %>
  <p>No reviews.</p>
<% end %>
  <% end %>

<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<a href="/restaurants/new">Add a restaurant</a>